//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Assignment1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Please fill in the required field")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please fill in the required field")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Please fill in the required field")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please fill in the required field")]
        [Range(1000, 50000000, ErrorMessage = "Salary Must be between 1000 to 50000000")]
        public Nullable<decimal> Salary { get; set; }
    }
}
